### ISSUE TITLE
[CHORE] Prevent Mainnet forking tests from executing with custom commit message prefix

### ISSUE THREAD

**Issue by drewstone** [webb-tools/protocol-solidity#215]
# Overview
To prevent the exhaustion of INFURA api keys, we should have a commit message prefix that prevents the execution of those tests. Something like this would allow us to develop and eventually make CI green on the entire test suite only after we're closer to the finish line for a PR.

## Message prefix: `[wip]`
```
git commit -m"[wip] this shouldn't execute the mainnet forking tests"
```

**Comment by dutterbutter** [comment]
Rather than make use of a commit message prefix, I suggest having a condition to avoid running _mainnet forking tests_ while the PR is in a **draft** state.

We can still run all other CI jobs as is, once the PR is in a 'ready to review' state the _mainnet forking tests_  would run accordingly and this would avoid forcing specific semantics on commit messages. Thoughts? @drewstone
